const test=require("node:test"),assert=require("node:assert/strict");
const validator=require("../src/curriculum-validator.js"),{CurriculumLoader}=require("../src/curriculum-loader.js"),importCore=require("../src/curriculum-import-core.js");
const {buildImportReport,toMarkdown}=require("../src/curriculum-import-report.js");
const pathPolicy=require("../src/curriculum-path-policy.js"),path=require("node:path");
const HASH="a".repeat(64),OBJECTIVE={id:"credit.objective.pipeline_test",world:"credit",sectionId:"credit.section.pipeline_test",title:"Technical fixture",statement:"Test-only objective record.",difficulty:"beginner",approvalStatus:"approved_locked",curriculumVersion:"test-v1",termIds:["credit.apr"],prerequisiteObjectiveIds:[],metadata:{order:0}},SECTION={id:"credit.section.pipeline_test",world:"credit",title:"Technical fixture section",approvalStatus:"approved_locked",curriculumVersion:"test-v1",objectiveIds:["credit.objective.pipeline_test"],metadata:{order:0}};
function exportFixture(){return {schemaVersion:1,curriculumVersion:"test-v1",world:"credit",generatedAt:"2026-07-12T12:00:00.000Z",source:{workbooks:[{fileName:"technical-fixture.xlsx",sha256:HASH}],approvalLogHash:HASH,controlledValuesHash:HASH},sections:[SECTION],objectives:[OBJECTIVE]}}
test("maps exact workbook headings without curriculum interpretation",()=>{const matrix=[["Objective ID","Supporting Term IDs","Order"],[OBJECTIVE.id,"credit.apr|credit.loan",3]],rows=importCore.mapDataset(matrix,{headerRow:1,fields:{id:"Objective ID","metadata.order":"Order"},listFields:{termIds:{header:"Supporting Term IDs",delimiter:"|"}}});assert.deepEqual(rows,[{id:OBJECTIVE.id,metadata:{order:3},termIds:["credit.apr","credit.loan"]}])});
test("validates a versioned export and builds runtime indexes",()=>{const data=exportFixture(),result=validator.validateCurriculum(data,{termIds:["credit.apr"]});assert.equal(result.valid,true,result.errors.join("\n"));const runtime=new CurriculumLoader({validator,termIds:["credit.apr"]}).load(JSON.stringify(data));assert.equal(runtime.sectionsById.get(SECTION.id).title,SECTION.title);assert.equal(runtime.objectivesForSection(SECTION.id)[0].id,OBJECTIVE.id);assert.equal(Object.isFrozen(runtime.data),true)});
test("rejects draft records, broken relationships, and premature future libraries",()=>{const data=exportFixture();data.sections[0]={...data.sections[0],approvalStatus:"draft",objectiveIds:[]};data.scenarios=[];const errors=validator.validateCurriculum(data,{termIds:["credit.apr"]}).errors.join("\n");assert.match(errors,/approved_locked/);assert.match(errors,/does not list objective/);assert.match(errors,/must not be exported/)});
test("rejects objective term IDs missing from the runtime term registry",()=>{const errors=validator.validateCurriculum(exportFixture(),{termIds:["credit.other"]}).errors.join("\n");assert.match(errors,/unknown term 'credit.apr'/)});
test("generates a passing curriculum import quality-gate report",()=>{const data=exportFixture(),validation=validator.validateCurriculum(data,{termIds:["credit.apr"]}),report=buildImportReport(data,validation);assert.equal(report.sectionsImported,1);assert.equal(report.objectivesImported,1);assert.equal(report.supportingTermReferences,1);assert.equal(report.validation.status,"PASS");assert.equal(report.runtimeJsonGenerated,true);assert.match(toMarkdown(report),/Runtime JSON generated: Yes/)});
test("reports validation failures before runtime JSON is allowed",()=>{const data=exportFixture();data.objectives.push({...OBJECTIVE,id:OBJECTIVE.id});const validation=validator.validateCurriculum(data,{termIds:["credit.apr"]}),report=buildImportReport(data,validation);assert.equal(report.duplicateIds.objectives.length,1);assert.equal(report.validation.status,"FAIL");assert.equal(report.runtimeJsonGenerated,false)});
test("enforces immutable workbook and generated-output boundaries for every world",()=>{const map="/project/curriculum/credit/approved/import-map.json",locations=pathPolicy.approvedPaths(map,"credit","1.0");assert.equal(locations.workbooksDir,path.normalize("/project/curriculum/credit/approved/workbooks"));assert.equal(locations.runtimeFile,path.normalize("/project/curriculum/credit/approved/runtime/credit-curriculum-v1.0.json"));assert.equal(pathPolicy.assertWorkbookPath(locations.workbooksDir,"/project/curriculum/credit/approved/workbooks/source.xlsx"),path.normalize("/project/curriculum/credit/approved/workbooks/source.xlsx"));assert.throws(()=>pathPolicy.assertWorkbookPath(locations.workbooksDir,"/project/curriculum/credit/approved/runtime/fake.xlsx"),/must be inside/)});
test("rejects world-specific directory mismatches",()=>{assert.throws(()=>pathPolicy.approvedPaths("/project/curriculum/credit/approved/import-map.json","banking","1.0"),/does not match/)});
