const test=require("node:test"),assert=require("node:assert/strict");
const learning=require("../learning-engine.js"),{loadContent,memoryStorage}=require("./helpers.js");
const {terms}=loadContent();
function engine(storage=memoryStorage(),clock={value:new Date("2026-01-01T12:00:00Z")}){return {instance:new learning.LearningEngine({terms,storage,now:()=>new Date(clock.value)}),storage,clock}}
test("migrates legacy Yield and review progress without content duplication",()=>{const storage=memoryStorage({yw_yield:"42.7",yw_review:JSON.stringify({TOKEN:3})}),{instance}=engine(storage);assert.equal(instance.save.saveVersion,3);assert.equal(instance.save.player.xp,43);assert.equal(instance.save.termProgress["crypto.token"].puzzle.timesSolved,1);assert.equal(JSON.stringify(instance.save.termProgress).includes("definition"),false)});
test("migrates version 2 saves, fills objective fields, and preserves unknown fields",()=>{const raw={saveVersion:2,customFutureField:{ok:true},player:{xp:9},termProgress:{"crypto.token":{dateUnlocked:"2026-01-01"}}},storage=memoryStorage({[learning.SAVE_KEY]:JSON.stringify(raw)}),{instance}=engine(storage);assert.equal(instance.save.saveVersion,3);assert.equal(instance.save.player.xp,9);assert.equal(instance.save.customFutureField.ok,true);assert.deepEqual(instance.save.objectiveProgress,{});assert.equal(instance.save.termProgress["crypto.token"].challenge.challengesSeen,0)});
test("recovers from malformed saves",()=>{const storage=memoryStorage({[learning.SAVE_KEY]:"{broken"}),{instance}=engine(storage);assert.equal(instance.save.saveVersion,3);assert.deepEqual(instance.save.termProgress,{})});
for(const [rating,expectedDays] of [["again",10/1440],["hard",1],["good",1],["easy",4]])test(`${rating} schedules the expected first interval`,()=>{const {instance}=engine();const result=instance.review("crypto.token",rating);assert.ok(Math.abs(result.review.currentInterval-expectedDays)<.00001);assert.ok(result.review.nextReviewDate)});
test("ease factor respects lower and upper boundaries",()=>{const {instance}=engine();for(let i=0;i<20;i++)instance.review("crypto.token","again");assert.equal(instance.progressFor("crypto.token").review.currentEaseFactor,1.3);for(let i=0;i<20;i++)instance.review("crypto.coin","easy");assert.equal(instance.progressFor("crypto.coin").review.currentEaseFactor,3)});
test("intervals progress and due reviews are selected by date",()=>{const {instance,clock}=engine();instance.review("crypto.token","good");assert.equal(instance.due("crypto").length,0);clock.value=new Date("2026-01-02T12:00:01Z");assert.equal(instance.due("crypto")[0].id,"crypto.token");instance.review("crypto.token","good");assert.equal(instance.progressFor("crypto.token").review.currentInterval,3)});
test("puzzle and challenge analytics remain separate",()=>{const {instance}=engine();instance.recordHint("crypto.token",{lettersRevealed:1});instance.recordPuzzleSolved("crypto.token",{solveTimeMs:5000});instance.recordChallenge("crypto.token",{correct:false,misconceptionFlag:"crypto.token.example"});const metrics=instance.termMetrics("crypto.token");assert.equal(metrics.puzzle.timesSolved,1);assert.equal(metrics.puzzle.hintsUsed,1);assert.equal(metrics.challenge.challengesIncorrect,1);assert.equal(metrics.challenge.challengeAccuracy,0);assert.deepEqual(metrics.challenge.misconceptionFlags,["crypto.token.example"])});
test("crossword completion alone cannot create full mastery",()=>{const {instance}=engine();for(let i=0;i<10;i++)instance.recordPuzzleSolved("crypto.token");assert.equal(instance.termMetrics("crypto.token").mastery.percent,20);assert.ok(instance.progressFor("crypto.token").masteryLevel<4)});
test("repeated applied success and reviews can set mastery date",()=>{const {instance}=engine();for(let i=0;i<2;i++)instance.recordPuzzleSolved("crypto.token");for(let i=0;i<3;i++)instance.recordChallenge("crypto.token",{correct:true});for(let i=0;i<3;i++)instance.review("crypto.token","easy");const progress=instance.progressFor("crypto.token");assert.equal(progress.masteryPercent,100);assert.ok(progress.dateMastered)});
test("review counts and term unlock are recorded",()=>{const {instance}=engine();instance.review("crypto.token","hard");const p=instance.progressFor("crypto.token");assert.equal(p.review.hardCount,1);assert.ok(p.dateUnlocked)});
