const test=require("node:test"),assert=require("node:assert/strict");
const learning=require("../learning-engine.js"),validator=require("../src/objective-validator.js"),objectivesApi=require("../src/objective-engine.js"),{memoryStorage}=require("./helpers.js");
const APR_TERM={id:"credit.apr",world:"credit",category:"borrowing_costs",difficulty:"beginner",word:"APR",normalizedWord:"apr",definition:"The yearly cost of borrowing money, including interest and certain fees.",pronunciation:"A-P-R",realLifeExample:"You finance a car at 7% APR. The APR helps estimate how much borrowing will cost over a year.",didYouKnow:"A loan with a lower monthly payment can still cost more overall if its APR is higher.",commonMistake:"Many people compare only monthly payments instead of comparing APR.",relatedTermIds:[],quickChallenge:{id:"credit.apr.compare",type:"compare_choices",prompt:"Which loan will usually cost less over time if all other terms are equal?",options:["10% APR","6% APR","Same cost"],correctAnswer:1,explanation:"When loan terms are otherwise the same, a lower APR generally means lower borrowing costs.",difficulty:"beginner",relatedTermId:"credit.apr"},xpValue:10,reviewWeight:1};
const OBJECTIVE={id:"credit.objective.test_apr",world:"credit",sectionId:"credit.test_section",title:"Technical test objective",statement:"Technical fixture only; not curriculum content.",difficulty:"beginner",approvalStatus:"approved_locked",curriculumVersion:"test-only",termIds:["credit.apr"],prerequisiteObjectiveIds:[],scenarioIds:["credit.scenario.test"],challengeIds:["credit.challenge.test"],metadata:{order:0,tags:["test"]}};
function setup(){const storage=memoryStorage(),engine=new learning.LearningEngine({terms:[APR_TERM],storage,now:()=>new Date("2026-07-12T12:00:00Z")}),objectiveEngine=new objectivesApi.ObjectiveEngine({objectives:[OBJECTIVE],learningEngine:engine,validator,worldId:"credit",config:{termMasteryThreshold:20}});return {engine,objectiveEngine,storage}}
test("accepts approved locked objectives with stable term relationships",()=>{const result=validator.validateObjectives([OBJECTIVE],{worldId:"credit",termIds:["credit.apr"]});assert.equal(result.valid,true,result.errors.join("\n"))});
test("does not require unapproved future scenario or challenge mappings",()=>{const {scenarioIds,challengeIds,...approvedNow}=OBJECTIVE,result=validator.validateObjectives([approvedNow],{worldId:"credit",termIds:["credit.apr"]});assert.equal(result.valid,true,result.errors.join("\n"));const {objectiveEngine}=(()=>{const storage=memoryStorage(),engine=new learning.LearningEngine({terms:[APR_TERM],storage}),objectiveEngine=new objectivesApi.ObjectiveEngine({objectives:[approvedNow],learningEngine:engine,validator,worldId:"credit"});return {objectiveEngine}})();assert.deepEqual(objectiveEngine.repository.get(approvedNow.id).scenarioIds,[]);assert.deepEqual(objectiveEngine.repository.get(approvedNow.id).challengeIds,[])});
test("rejects unapproved objectives and unknown term references",()=>{const invalid={...OBJECTIVE,approvalStatus:"draft",termIds:["credit.missing"]},errors=validator.validateObjectives([invalid],{worldId:"credit",termIds:["credit.apr"]}).errors.join("\n");assert.match(errors,/approved_locked/);assert.match(errors,/unknown term/)});
test("rejects duplicate ids and invalid prerequisite references",()=>{const duplicate={...OBJECTIVE,metadata:{order:1}},errors=validator.validateObjectives([OBJECTIVE,duplicate],{worldId:"credit",termIds:["credit.apr"]}).errors.join("\n");assert.match(errors,/Duplicate objective id/);const badPrereq={...OBJECTIVE,prerequisiteObjectiveIds:["credit.objective.missing"]};assert.match(validator.validateObjectives([badPrereq],{worldId:"credit",termIds:["credit.apr"]}).errors.join("\n"),/unknown prerequisite/)});
test("stores objective progress by id without duplicating curriculum",()=>{const {engine,objectiveEngine}=setup();objectiveEngine.refresh(OBJECTIVE.id);assert.ok(engine.save.objectiveProgress[OBJECTIVE.id]);assert.equal(JSON.stringify(engine.save.objectiveProgress).includes(OBJECTIVE.statement),false)});
test("objective completion combines term mastery and future library results",()=>{const {engine,objectiveEngine}=setup();for(let i=0;i<2;i++)engine.recordPuzzleSolved("credit.apr");objectiveEngine.recordScenarioResult(OBJECTIVE.id,"credit.scenario.test",{correct:true});const progress=objectiveEngine.recordChallengeResult(OBJECTIVE.id,"credit.challenge.test",{correct:true});assert.equal(progress.status,"completed");assert.equal(progress.completionPercent,100);assert.ok(progress.dateCompleted)});
test("scenario and challenge library metrics remain separately addressable",()=>{const {engine,objectiveEngine}=setup();objectiveEngine.recordScenarioResult(OBJECTIVE.id,"credit.scenario.test",{correct:false});objectiveEngine.recordChallengeResult(OBJECTIVE.id,"credit.challenge.test",{correct:true});assert.equal(engine.save.scenarioProgress["credit.scenario.test"].incorrect,1);assert.equal(engine.save.libraryChallengeProgress["credit.challenge.test"].correct,1)});
test("world objective stats report honest totals",()=>{const {objectiveEngine}=setup(),stats=objectiveEngine.worldStats("credit");assert.equal(stats.totalObjectives,1);assert.equal(stats.completedObjectives,0);assert.equal(stats.completionPercent,0)});
