(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.FinLitGameEngine=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  function canForm(word,letters){const available=[...letters];return [...word].every(letter=>{const index=available.indexOf(letter);if(index<0)return false;available.splice(index,1);return true})}
  function evaluateWord(word,level,foundWords,bonusWords){if(!word)return {status:"empty"};if(foundWords.has(word))return {status:"duplicate"};if(level.words.includes(word))return {status:"target",word};if(bonusWords.includes(word)&&canForm(word,level.letters))return {status:"bonus",word};return {status:"invalid",word}}
  function canPlace(word,row,column,direction,occupied){for(let i=0;i<word.length;i++){const key=`${row+(direction==="v"?i:0)},${column+(direction==="h"?i:0)}`;if(occupied.has(key)&&occupied.get(key)!==word[i])return false}return true}
  function layoutWords(words){const occupied=new Map(),placed=[];let minRow=0,minColumn=0;words.forEach((word,wordIndex)=>{let best=null;if(!wordIndex)best={r:2,c:1,dir:"h"};else for(const placedWord of placed)for(let a=0;a<word.length;a++)for(let b=0;b<placedWord.word.length;b++)if(word[a]===placedWord.word[b]){const direction=placedWord.dir==="h"?"v":"h",row=placedWord.r+(placedWord.dir==="v"?b:0)-(direction==="v"?a:0),column=placedWord.c+(placedWord.dir==="h"?b:0)-(direction==="h"?a:0);if(canPlace(word,row,column,direction,occupied)){best={r:row,c:column,dir:direction};break}}if(!best){const usedRows=placed.map(item=>item.r+(item.dir==="v"?item.word.length:0));best={r:Math.max(...usedRows,0)+1,c:1,dir:"h"}}placed.push({...best,word});for(let i=0;i<word.length;i++){const row=best.r+(best.dir==="v"?i:0),column=best.c+(best.dir==="h"?i:0);occupied.set(`${row},${column}`,word[i]);minRow=Math.min(minRow,row);minColumn=Math.min(minColumn,column)}});return placed.map(item=>({...item,r:item.r-minRow,c:item.c-minColumn}))}
  function wheelFor(words){const counts={};words.forEach(word=>{const own={};[...word].forEach(letter=>own[letter]=(own[letter]||0)+1);Object.entries(own).forEach(([letter,count])=>counts[letter]=Math.max(counts[letter]||0,count))});return Object.entries(counts).flatMap(([letter,count])=>Array(count).fill(letter))}
  function positionFor(placement,index){return {row:placement.r+(placement.dir==="v"?index:0),column:placement.c+(placement.dir==="h"?index:0)}}
  function isCrossingVisible(word,index,words,foundWords){const placements=layoutWords(words),target=placements.find(item=>item.word===word);if(!target)return false;const position=positionFor(target,index);return placements.some(item=>foundWords.has(item.word)&&[...item.word].some((_,i)=>{const other=positionFor(item,i);return other.row===position.row&&other.column===position.column}))}
  function nextHint(words,foundWords,hints){const unfinished=words.filter(word=>!foundWords.has(word));for(const word of unfinished){for(let index=0;index<word.length;index++){if(!hints.has(`${word}:${index}`)&&!isCrossingVisible(word,index,words,foundWords))return {word,index,letter:word[index]}}}return null}
  return {canForm,evaluateWord,layoutWords,wheelFor,isCrossingVisible,nextHint};
});
