(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.FinLitObjectives=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  const DEFAULT_CONFIG=Object.freeze({termWeight:.6,scenarioWeight:.2,challengeWeight:.2,termMasteryThreshold:75});
  const iso=date=>date.toISOString();
  function emptyObjectiveProgress(){return {status:"not_started",completionPercent:0,termMasteryPercent:0,scenarioCompletionPercent:0,challengeCompletionPercent:0,lastActivity:null,dateCompleted:null}}
  class ObjectiveRepository{
    constructor(objectives,{validator,worldId,termIds}){validator.assertValidObjectives(objectives,{worldId,termIds});this.byId=new Map();this.idsByWorld=new Map();objectives.forEach(objective=>{const frozen=Object.freeze({...objective,termIds:Object.freeze([...objective.termIds]),prerequisiteObjectiveIds:Object.freeze([...objective.prerequisiteObjectiveIds]),scenarioIds:Object.freeze([...(objective.scenarioIds||[])]),challengeIds:Object.freeze([...(objective.challengeIds||[])]),metadata:Object.freeze({...objective.metadata})});this.byId.set(frozen.id,frozen);if(!this.idsByWorld.has(frozen.world))this.idsByWorld.set(frozen.world,[]);this.idsByWorld.get(frozen.world).push(frozen.id)});this.idsByWorld.forEach(ids=>ids.sort((a,b)=>this.byId.get(a).metadata.order-this.byId.get(b).metadata.order))}
    get(id){return this.byId.get(id)||null}forWorld(world){return (this.idsByWorld.get(world)||[]).map(id=>this.byId.get(id))}
  }
  class ObjectiveEngine{
    constructor({objectives,learningEngine,validator,worldId,config={},now=()=>new Date()}){this.learning=learningEngine;this.now=now;this.config=Object.freeze({...DEFAULT_CONFIG,...config});this.repository=new ObjectiveRepository(objectives,{validator,worldId,termIds:[...learningEngine.repository.byId.keys()]});const save=learningEngine.save;save.objectiveProgress=save.objectiveProgress||{};save.scenarioProgress=save.scenarioProgress||{};save.libraryChallengeProgress=save.libraryChallengeProgress||{};this.refreshWorld(worldId);learningEngine.persist()}
    progressFor(id){if(!this.repository.get(id))throw new Error(`Unknown objective id: ${id}`);if(!this.learning.save.objectiveProgress[id])this.learning.save.objectiveProgress[id]=emptyObjectiveProgress();return this.learning.save.objectiveProgress[id]}
    recordLibraryResult(storeName,id,{correct}){const store=this.learning.save[storeName],record=store[id]||{attempts:0,correct:0,incorrect:0,lastResult:null,lastActivity:null};record.attempts++;correct?record.correct++:record.incorrect++;record.lastResult=Boolean(correct);record.lastActivity=iso(this.now());store[id]=record;return record}
    recordScenarioResult(objectiveId,scenarioId,result){const objective=this.repository.get(objectiveId);if(!objective?.scenarioIds.includes(scenarioId))throw new Error(`Scenario '${scenarioId}' is not linked to objective '${objectiveId}'.`);this.recordLibraryResult("scenarioProgress",scenarioId,result);return this.refresh(objectiveId)}
    recordChallengeResult(objectiveId,challengeId,result){const objective=this.repository.get(objectiveId);if(!objective?.challengeIds.includes(challengeId))throw new Error(`Challenge '${challengeId}' is not linked to objective '${objectiveId}'.`);this.recordLibraryResult("libraryChallengeProgress",challengeId,result);return this.refresh(objectiveId)}
    refresh(id){
      const objective=this.repository.get(id),progress=this.progressFor(id),termValues=objective.termIds.map(termId=>this.learning.save.termProgress[termId]?.masteryPercent||0),termAverage=termValues.reduce((sum,value)=>sum+value,0)/termValues.length;
      const scenarioCorrect=objective.scenarioIds.filter(itemId=>this.learning.save.scenarioProgress[itemId]?.correct>0).length,challengeCorrect=objective.challengeIds.filter(itemId=>this.learning.save.libraryChallengeProgress[itemId]?.correct>0).length;
      const termScore=Math.min(100,termAverage/this.config.termMasteryThreshold*100),scenarioScore=objective.scenarioIds.length?scenarioCorrect/objective.scenarioIds.length*100:null,challengeScore=objective.challengeIds.length?challengeCorrect/objective.challengeIds.length*100:null;
      const components=[{score:termScore,weight:this.config.termWeight},scenarioScore===null?null:{score:scenarioScore,weight:this.config.scenarioWeight},challengeScore===null?null:{score:challengeScore,weight:this.config.challengeWeight}].filter(Boolean),weightTotal=components.reduce((sum,item)=>sum+item.weight,0),completion=Math.round(components.reduce((sum,item)=>sum+item.score*item.weight,0)/weightTotal);
      progress.termMasteryPercent=Math.round(termAverage);progress.scenarioCompletionPercent=Math.round(scenarioScore||0);progress.challengeCompletionPercent=Math.round(challengeScore||0);progress.completionPercent=completion;progress.status=completion===0?"not_started":completion===100?"completed":"in_progress";progress.lastActivity=iso(this.now());if(progress.status==="completed"&&!progress.dateCompleted)progress.dateCompleted=iso(this.now());if(progress.status!=="completed")progress.dateCompleted=null;this.learning.persist();return {...progress}
    }
    refreshWorld(world){return this.repository.forWorld(world).map(objective=>({objective,progress:this.refresh(objective.id)}))}
    worldStats(world){const rows=this.refreshWorld(world),complete=rows.filter(row=>row.progress.status==="completed").length,average=rows.length?Math.round(rows.reduce((sum,row)=>sum+row.progress.completionPercent,0)/rows.length):0;return {world,totalObjectives:rows.length,completedObjectives:complete,remainingObjectives:rows.length-complete,completionPercent:average}}
  }
  return {ObjectiveEngine,ObjectiveRepository,DEFAULT_CONFIG,emptyObjectiveProgress};
});
